### PR TITLE
V2.3 fix

### PR DESCRIPTION
**Pull request by yunqu**

### CODE REVIEW

**Comment by yunqu** [comment]
I have something additional to fix. So please leave it on for now.

**Comment by sfox14** [comment]
sure. will do

**Comment by yunqu** [comment]
@sfox14  This PR should be fine now. Just tested on z1; works fine.

You can test on other boards as well. but notice that we do not have to build on the arm anymore.

**Comment by sfox14** [comment]
Nice. This is interesting

**Pull request merged**
